version: '3.8'
services:
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=freighthive
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    depends_on:
      - db
    restart: always

volumes:
  db:
    driver: local
