version: '3.8'
services:
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=freighthive
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - freighthive-app

  server:
    container_name: server
    image: freighthive-server
    ports:
      - '3333:3333'
    depends_on:
      - db
    networks:
      - freighthive-app

networks:
  freighthive-app:
    driver: bridge

volumes:
  db:
    driver: local
